### ISSUE TITLE
Fetch variables from all environment scopes

### ISSUE THREAD

**Issue by Jony321** [lingrino/glen#255]
Hello!
Cool project, saved me a lot of time, thanks to all the participants for the work!
I'm using glen to locally test pipelines in conjunction with [gitlab-ci-local](https://github.com/firecow/gitlab-ci-local) and I have a question:
Is it possible to add an option to load variables across all environment scopes?
I have several environments, but when I upload variables from gitlab, I get a variable for only one environment, therefore, in order to deploy to another host, for example, I need to open gitlab and look for the corresponding variable there.

**Comment by lingrino** [comment]
👋 @Jony321 I'm not very familiar with gitlab these days so I may be missing something but I think what you're asking is already the default behavior.

If I have two envs `enva` and `envb` and I have a variable `foo=bar` in the first and `baz=bix` in the second then when you run `glen` it should output both variables right? That's how it is working for me. If instead you have `foo=bar` in the first and `foo=baz` in the second then it will only output one of them because they have conflicting keys. Is that what you're running into? In that case it would be possible for glen to support duplicate keys but it wouldn't be an easy contribution because the variables are currently stored in a map.

Let me know what you're seeing and maybe I can try to help.

**Comment by Jony321** [comment]
@lingrino 
Hello and sorry for delay)
Yes, I meant the option when we have duplicate variable names in different environment scopes.
I'd like to generate a file with a full set of variables, including duplicates, and then just comment out the environment scope(s) I don't need.
Unfortunately I'm bad at development, but I think it would be possible to add an environment scope label to the output of duplicate variables, like so:
```
VAR_KEY=VAR_VALUE 		# environment scope name

SSH_HOST=staging.example.com	# staging
SSH_HOST=production.example.com	# production
SSH_HOST=test.example.com	# all
```

I noticed that the utility used at the base of `glen` (`go-gitlab`) allows you to get information about the environment scopes, but I could not figure out how to add this to `glen`.
I think of this functionality as a separate option, `--all-environments`, for example, which will only allow you to get variables from all environments and process them as needed manually.

To understand the reason for this request:
Using `glen`, I generate a file with a set of variables for `gitlab-ci-local` and run a local deploy, but due to the fact that I cannot determine from which environment set the variables came from, I have to manually check each variable to be sure that I  perform a deployment to the host I need with the necessary options.

By executing the command:
`glen -o json | jq -r 'to_entries|map("\(.key): \"\(.value|tostring)\"")|.[]' > .gitlab-ci-local-variables.yml`

I get a file of the correct (for `gitlab-ci-local`) format, but I still can't run `gitlab-ci-local` until I check all the variables against the same environment set.  For example, this variables will be different for different environment scopes, and now `glen` mixes them:
```
NAME: "some_name"
VERSION: "v1.0.0"
SSH_HOST: "some_host"
SSH_PORT: "22"
SSH_USER: "some_user"
TARGET_HOST_SSH_PRIVATE_KEY: "some_key"
```

That seems to be it, thank you for your attention)

**Comment by lingrino** [comment]
@Jony321 Thanks for the detailed issue. I agree it would be great if `glen` supported this use case. Unfortunately it's not a quick feature and I'm not longer a heavy gitlab user so I probably won't ever find the time to work on this. If someone is interested in supporting this as a contribution I would be happy to review a PR. Thanks again!
