### ISSUE TITLE
When using -r it should output what it can get

### ISSUE THREAD

**Issue by holyspidoo** [lingrino/glen#34]
When using -r, if your token only grants you access to one level up in groups, it should still output what it can get (or maybe have a new option for allowed recursive)

**Comment by lingrino** [comment]
I agree this would be a great addition. I'm ok with making this the default functionality (returning what we have instead of erroring) instead of adding a new option. I may find some time next week to work on this or feel free to add your own contribution sooner.

**Comment by lingrino** [comment]
👋 @holyspidoo It looks like this may have been fixed in #36 since we now keep iterating on an error. Are you still having this issue using `v1.3.0`?

**Comment by lingrino** [comment]
Closing this as I believe it was fixed in #36. Please reopen if you're still having an issue!
